"""Data models for the Provenance Shard."""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional


class ChainStatus(Enum):
    """Status of an evidence chain."""
    DRAFT = "draft"
    ACTIVE = "active"
    VERIFIED = "verified"
    COMPLETED = "completed"
    ARCHIVED = "archived"


class LinkType(Enum):
    """Type of relationship between artifacts."""
    DERIVED_FROM = "derived_from"          # Target derived from source
    TRANSFORMED_TO = "transformed_to"      # Source transformed to target
    EXTRACTED_FROM = "extracted_from"      # Target extracted from source
    GENERATED_BY = "generated_by"          # Target generated by source process
    USED_BY = "used_by"                    # Source used by target process
    SUPPORTS = "supports"                  # Source supports target claim
    CONTRADICTS = "contradicts"            # Source contradicts target claim
    RELATED_TO = "related_to"              # Generic relationship
    VERSION_OF = "version_of"              # Target is version of source
    COPY_OF = "copy_of"                    # Target is copy of source


class ArtifactType(Enum):
    """Type of tracked artifact."""
    DOCUMENT = "document"
    ENTITY = "entity"
    CLAIM = "claim"
    EVIDENCE = "evidence"
    HYPOTHESIS = "hypothesis"
    MATRIX = "matrix"
    REPORT = "report"
    EMBEDDING = "embedding"
    EXTRACTION = "extraction"
    TIMELINE = "timeline"
    GRAPH = "graph"
    SUMMARY = "summary"


class EventType(Enum):
    """Type of audit event."""
    CHAIN_CREATED = "chain_created"
    CHAIN_UPDATED = "chain_updated"
    CHAIN_DELETED = "chain_deleted"
    LINK_ADDED = "link_added"
    LINK_REMOVED = "link_removed"
    LINK_VERIFIED = "link_verified"
    ARTIFACT_TRACKED = "artifact_tracked"
    AUDIT_GENERATED = "audit_generated"
    EXPORT_COMPLETED = "export_completed"


@dataclass
class EvidenceChain:
    """An evidence chain tracking artifact provenance."""
    id: str
    title: str
    description: str = ""
    status: ChainStatus = ChainStatus.DRAFT

    # Timestamps
    created_at: datetime = field(default_factory=datetime.utcnow)
    updated_at: datetime = field(default_factory=datetime.utcnow)

    # Ownership
    created_by: Optional[str] = None
    project_id: Optional[str] = None

    # Statistics
    link_count: int = 0
    artifact_count: int = 0

    # Metadata
    metadata: Dict[str, Any] = field(default_factory=dict)
    tags: List[str] = field(default_factory=list)

    # Verification
    verified: bool = False
    verified_by: Optional[str] = None
    verified_at: Optional[datetime] = None
    verification_notes: str = ""


@dataclass
class ProvenanceLink:
    """A link between two artifacts in a provenance chain."""
    id: str
    chain_id: str

    # Link endpoints
    source_artifact_id: str
    target_artifact_id: str

    # Link properties
    link_type: LinkType
    confidence: float = 1.0  # 0.0 to 1.0

    # Timestamps
    created_at: datetime = field(default_factory=datetime.utcnow)

    # Verification
    verified: bool = False
    verified_by: Optional[str] = None
    verified_at: Optional[datetime] = None

    # Additional context
    metadata: Dict[str, Any] = field(default_factory=dict)
    notes: str = ""

    # Transformation details (if applicable)
    transformation_process: Optional[str] = None
    transformation_params: Dict[str, Any] = field(default_factory=dict)


@dataclass
class TrackedArtifact:
    """An artifact being tracked in the provenance system."""
    id: str  # Internal ID
    artifact_id: str  # External artifact ID
    artifact_type: ArtifactType
    shard_name: str  # Which shard created this

    # Timestamps
    created_at: datetime = field(default_factory=datetime.utcnow)

    # Context
    project_id: Optional[str] = None

    # Metadata from source shard
    metadata: Dict[str, Any] = field(default_factory=dict)

    # Lineage statistics
    upstream_count: int = 0  # Number of dependencies
    downstream_count: int = 0  # Number of dependents


@dataclass
class AuditRecord:
    """An audit log record."""
    id: str

    # Event details
    event_type: EventType
    event_source: str  # Shard or service that triggered event
    event_data: Dict[str, Any]

    # Timestamp
    timestamp: datetime = field(default_factory=datetime.utcnow)

    # Context
    chain_id: Optional[str] = None
    user_id: Optional[str] = None

    # Additional metadata
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class LineageNode:
    """A node in a lineage graph."""
    id: str
    artifact_id: str
    artifact_type: ArtifactType
    shard_name: str
    label: str

    # Visual properties (for graph rendering)
    level: int = 0  # Depth in graph
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class LineageEdge:
    """An edge in a lineage graph."""
    source: str  # Source node ID
    target: str  # Target node ID
    link_type: LinkType
    confidence: float

    # Visual properties
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class LineageGraph:
    """A complete lineage graph for an artifact."""
    artifact_id: str
    direction: str  # upstream, downstream, both

    nodes: List[LineageNode] = field(default_factory=list)
    edges: List[LineageEdge] = field(default_factory=list)

    # Graph statistics
    total_nodes: int = 0
    total_edges: int = 0
    max_depth: int = 0

    # Metadata
    generated_at: datetime = field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class VerificationResult:
    """Result of chain verification."""
    chain_id: str
    verified: bool

    # Issues found during verification
    issues: List[Dict[str, Any]] = field(default_factory=list)
    warnings: List[Dict[str, Any]] = field(default_factory=list)

    # Verification details
    checked_at: datetime = field(default_factory=datetime.utcnow)
    checked_by: Optional[str] = None

    # Statistics
    links_checked: int = 0
    links_verified: int = 0
    artifacts_checked: int = 0

    # Metadata
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ChainExport:
    """Exported chain data."""
    chain: EvidenceChain
    links: List[ProvenanceLink]
    artifacts: List[TrackedArtifact]
    audit_trail: List[AuditRecord]

    # Export metadata
    exported_at: datetime = field(default_factory=datetime.utcnow)
    exported_by: Optional[str] = None
    export_format: str = "json"

    # Export options
    include_metadata: bool = True
    include_audit: bool = True
    include_verification: bool = True


# =============================================================================
# Metadata Forensics Models
# =============================================================================


class ForensicScanStatus(Enum):
    """Status of a forensic scan."""
    PENDING = "pending"
    COMPLETED = "completed"
    FAILED = "failed"
    PARTIAL = "partial"


class IntegrityStatus(Enum):
    """Integrity status of a document."""
    CLEAN = "clean"
    SUSPICIOUS = "suspicious"
    TAMPERED = "tampered"
    UNKNOWN = "unknown"


class RelationshipType(Enum):
    """Type of relationship between documents based on metadata."""
    COPY = "copy"
    DERIVATIVE = "derivative"
    SAME_SOURCE = "same_source"
    SAME_AUTHOR = "same_author"
    SAME_CAMERA = "same_camera"
    UNRELATED = "unrelated"


@dataclass
class ExifData:
    """EXIF metadata from images."""
    make: Optional[str] = None
    model: Optional[str] = None
    serial_number: Optional[str] = None
    lens_model: Optional[str] = None

    datetime_original: Optional[datetime] = None
    datetime_digitized: Optional[datetime] = None
    datetime_modified: Optional[datetime] = None

    gps_latitude: Optional[float] = None
    gps_longitude: Optional[float] = None
    gps_altitude: Optional[float] = None

    software: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None

    raw_data: Dict[str, Any] = field(default_factory=dict)


@dataclass
class PdfMetadata:
    """PDF document metadata."""
    title: Optional[str] = None
    author: Optional[str] = None
    subject: Optional[str] = None
    creator: Optional[str] = None
    producer: Optional[str] = None
    creation_date: Optional[datetime] = None
    modification_date: Optional[datetime] = None
    keywords: List[str] = field(default_factory=list)
    xmp_data: Dict[str, Any] = field(default_factory=dict)
    page_count: int = 0
    pdf_version: Optional[str] = None
    is_encrypted: bool = False


@dataclass
class OfficeMetadata:
    """Office document (docx, xlsx, pptx) metadata."""
    title: Optional[str] = None
    author: Optional[str] = None
    subject: Optional[str] = None
    company: Optional[str] = None
    manager: Optional[str] = None
    created: Optional[datetime] = None
    modified: Optional[datetime] = None
    last_modified_by: Optional[str] = None
    revision: Optional[int] = None
    keywords: List[str] = field(default_factory=list)
    category: Optional[str] = None
    comments: Optional[str] = None
    raw_data: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ForensicFinding:
    """A forensic analysis finding."""
    finding_type: str  # timestamp_inconsistency, metadata_stripped, etc.
    severity: str  # low, medium, high, critical
    description: str
    evidence: Dict[str, Any] = field(default_factory=dict)
    confidence: float = 1.0


@dataclass
class TimelineEvent:
    """An event in document timeline reconstructed from metadata."""
    id: str
    doc_id: str
    event_type: str  # created, modified, accessed, printed
    event_timestamp: Optional[datetime] = None
    event_source: str = ""  # exif, pdf, office, filesystem
    event_actor: Optional[str] = None
    event_details: Dict[str, Any] = field(default_factory=dict)
    confidence: float = 1.0
    is_estimated: bool = False


@dataclass
class MetadataForensicScan:
    """Complete forensic scan result."""
    id: str
    doc_id: str
    scan_status: ForensicScanStatus = ForensicScanStatus.PENDING

    # File hashes
    file_hash_md5: Optional[str] = None
    file_hash_sha256: Optional[str] = None
    file_hash_sha512: Optional[str] = None
    file_size: Optional[int] = None

    # Extracted metadata by type
    exif_data: Optional[ExifData] = None
    pdf_metadata: Optional[PdfMetadata] = None
    office_metadata: Optional[OfficeMetadata] = None

    # Forensic findings
    findings: List[ForensicFinding] = field(default_factory=list)
    integrity_status: IntegrityStatus = IntegrityStatus.UNKNOWN
    confidence_score: float = 0.0

    # Reconstructed timeline
    timeline_events: List[TimelineEvent] = field(default_factory=list)

    # Metadata
    scanned_at: datetime = field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class MetadataComparison:
    """Comparison between two documents' metadata."""
    id: str
    source_doc_id: str
    target_doc_id: str
    comparison_type: str

    match_score: float = 0.0
    differences: List[Dict[str, Any]] = field(default_factory=list)
    similarities: List[Dict[str, Any]] = field(default_factory=list)

    relationship_type: Optional[RelationshipType] = None
    confidence: float = 0.0

    created_at: datetime = field(default_factory=datetime.utcnow)
    created_by: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ForensicStats:
    """Statistics about forensic scans."""
    total_scans: int = 0
    scans_by_status: Dict[str, int] = field(default_factory=dict)
    documents_with_findings: int = 0
    integrity_clean: int = 0
    integrity_suspicious: int = 0
    integrity_tampered: int = 0
    average_confidence: float = 0.0
    calculated_at: datetime = field(default_factory=datetime.utcnow)
